### ISSUE TITLE
Include lighter icons for dark menu bars

### ISSUE THREAD

**Issue by benjamincharity** [therealklanni/hotel-clerk#1]
The current icon looks invisible on a dark background:

<img width="384" alt="preview - screen shot 2016-04-03 at 11 05 18 am - screen shot april 3 2016 at 11 05 am" src="https://cloud.githubusercontent.com/assets/270193/14233087/41f97406-f98c-11e5-923a-ccab4fe4a4ff.png">

**Comment by therealklanni** [comment]
I'm happy to accept a PR if you want to take a swing at it! Thanks :)

**Comment by benjamincharity** [comment]
Closed via https://github.com/therealklanni/hotel-clerk/pull/3
