### ISSUE TITLE
Can't go "Back" after clicking "README" from menu icon

### ISSUE THREAD

**Issue by theednaffattack** [therealklanni/hotel-clerk#2]
Hi,

I clicked the README when I initially installed the app and now I can't seem to get back to viewing my local dev servers. Right-clicks are disabled and modifier keys like CTRL and CMD don't do anything either. I can't relaunch the menu app so I assume I'll need to restart my computer to get this behavior to change.

**Comment by therealklanni** [comment]
You can kill the process from the commandline and restart it. This was built with an older (new at the time) version of Electron and should be updated to the latest version. We probably need to add a context menu to the toolbar icon as well, but that's a separate issue.

If you want to submit a PR I'll happily accept. :metal:

**Comment by benjamincharity** [comment]
@Agent5 you can also click the menu bar icon and then hit `command + q` and hotel will quit. Easy enough until a context menu is added. 👍

**Comment by therealklanni** [comment]
I wasn't even aware of that, thanks for sharing the tip!

**Comment by therealklanni** [comment]
Fixed by #5
