### ISSUE TITLE
Why is the release so big?

### ISSUE THREAD

**Issue by devkhan** [therealklanni/hotel-clerk#7]
The latest release is ~112 MB, which seems really large for a simple menu bar app. There is just a few files in the repo, does it package something else into it which increases its size?

**Comment by therealklanni** [comment]
Yes, it's Electron itself.

**Comment by Grawl** [comment]
Not it's 329 MB unarchived .app file and it's still an issue for such a tiny tool

**Comment by therealklanni** [comment]
Again the size comes from Electron. If you or someone else is interested in updating the Electron version and submitting a PR, that may drastically reduce the size, and I would appreciate the contribution. I might have time to do it at some point, but it's pretty low priority for me right now.
