### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by adius** [therealklanni/hotel-clerk#9]
That's all I see:

<img width="402" alt="screen shot 2018-01-15 at 00 04 48" src="https://user-images.githubusercontent.com/969983/34922445-c2d4de6a-f987-11e7-96b0-9645047edcde.png">

**Comment by therealklanni** [comment]
Thanks. I'm guessing there was a major change in the newer version of hotel.

**Comment by yagudaev** [comment]
+1 same issue, love hotel clerk. I miss it :'( now.

**Comment by CollinDaugherty** [comment]
Are there any plans to fix this issue?

**Comment by yagudaev** [comment]
https://github.com/therealklanni/hotel-clerk/pull/10 created a PR to fix it. You can download the fixed binary here for now: https://github.com/nano3labs/hotel-clerk/releases.

@CollinDaugherty and @adius

**Comment by therealklanni** [comment]
Fixed by #10 Thanks to @yagudaev 

v1.1.2 released

**Comment by yagudaev** [comment]
Awesome thank you :). Hotel-Clerk is awesome thanks for putting it together
